package com.cdac.filesyncdsk.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.io.File;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;

/**
 * File Meta class
 *
 * @author Mahima Choudha
 * @version 1
 * @since 1
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class FileMetaJsonResponse {

    /**
     * SIP Creator
     */
    private Long sipCreator;
    /**
     * Unique record identifier
     */
    private String uuid;
    /**
     * Record identifier
     */
    private String identifier;
    /**
     * Name of file
     */
    private String fileName;
    /**
     * Size of file
     */
    private long fileSize;
    /**
     * Type of file
     */
    private String fileType;
    /**
     * Category of file
     */
    private String fileCategory;
    /**
     * Location of record
     */
    private String location;
    /**
     * Parent object unique record identifier
     */
    private String parentObjectUUID;
    /**
     * Record draft on date
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    private Date draftOn;
    /**
     * Main object
     */
    private FileMetaJsonResponse mainObject;
    /**
     * Enclosures
     */
    private List<FileMetaJsonResponse> enclosures;
    /**
     * Status of pid
     */
    private Boolean pidStatus;
    /**
     * Subfond id
     */
    private long subfondID;
    /**
     * profile of record
     */
    private String profile;
    /**
     * Checksum of record
     */
    private String checksum;
    /**
     * Is format validation failed or not
     */
    private boolean isFormatVidaltionFailed;
    /**
     * field is used to set os for pdfa generated by our system (i.e if jpegs
     * are uploaded as a single pdf). Set this property only for above case. and
     * don't set for other cases.
     */
    private String operatingSystem;

    /**
     * unique filename generated by custom method 
     */
    private String UniqueFileName;

    /**
     * file bytes for copying file to server 
     */
    private byte[] fileBytes;

    /**
     * success or fail status on copying the file
     */
    private String status;

    /**
     * Actual file to be uploaded
     */
    private File file;
    
    /**
     * Folder name to be zipped on server
     */
    private String folderOnServer;

    /**
     * give value of isFormatVidaltionFailed property
     *
     * @return
     */
    public boolean isIsFormatVidaltionFailed() {
        return isFormatVidaltionFailed;
    }

    /**
     * give value of isFormatVidaltionFailed property
     *
     * @param isFormatVidaltionFailed
     */
    public void setIsFormatVidaltionFailed(boolean isFormatVidaltionFailed) {
        this.isFormatVidaltionFailed = isFormatVidaltionFailed;
    }

    /**
     * give value of checksum property
     *
     * @return
     */
    public String getChecksum() {
        return checksum;
    }

    /**
     * set value of checksum property
     *
     * @param checksum
     */
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    /**
     * give value of profile property
     *
     * @return
     */
    public String getProfile() {
        return profile;
    }

    /**
     * set value of profile property
     *
     * @param profile
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * give value of subfondID property
     *
     * @return
     */
    public long getSubfondID() {
        return subfondID;
    }

    /**
     * set value of subfondID property
     *
     * @param subfondID
     */
    public void setSubfondID(long subfondID) {
        this.subfondID = subfondID;
    }

    /**
     * give value of draftOn property
     *
     * @return
     */
    public Date getDraftOn() {
        return draftOn;
    }

    /**
     * give value of pidStatus property
     *
     * @return
     */
    public Boolean getPidStatus() {
        return pidStatus;
    }

    /**
     * set value of pidStatus property
     *
     * @param pidStatus
     */
    public void setPidStatus(Boolean pidStatus) {
        this.pidStatus = pidStatus;
    }

    /**
     * set value of draftOn property
     *
     * @param draftOn
     */
    public void setDraftOn(Date draftOn) {
        this.draftOn = draftOn;
    }

    /**
     * set value of sipCreator property
     *
     * @return
     */
    public Long getSipCreator() {
        return sipCreator;
    }

    /**
     * set value of sipCreator property
     *
     * @param sipCreator
     */
    public void setSipCreator(Long sipCreator) {
        this.sipCreator = sipCreator;
    }

    /**
     * give value of identifier property
     *
     * @return
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * set value of identifier property
     *
     * @param identifier
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * give value of enclosures property
     *
     * @return
     */
    public List<FileMetaJsonResponse> getEnclosures() {
        if (enclosures == null) {
            enclosures = new LinkedList<>();
        }
        return enclosures;
    }

    /**
     * set value of enclosures property
     *
     * @param enclosures
     */
    public void setEnclosures(List<FileMetaJsonResponse> enclosures) {
        this.enclosures = enclosures;
    }

    /**
     * give value of location property
     *
     * @return
     */
    public String getLocation() {
        return location;
    }

    /**
     * set value of location property
     *
     * @param location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * give value of uuid property
     *
     * @return
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * set value of uuid property
     *
     * @param uuid
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * give value of parentObjectUUID property
     *
     * @return
     */
    public String getParentObjectUUID() {
        return parentObjectUUID;
    }

    /**
     * set value of parentObjectUUID property
     *
     * @param parentObjectUUID
     */
    public void setParentObjectUUID(String parentObjectUUID) {
        this.parentObjectUUID = parentObjectUUID;
    }

    /**
     * give value of fileCategory property
     *
     * @return
     */
    public String getFileCategory() {
        return fileCategory;
    }

    /**
     * set value of fileCategory property
     *
     * @param fileCategory
     */
    public void setFileCategory(String fileCategory) {
        this.fileCategory = fileCategory;
    }

    /**
     * give value of fileName property
     *
     * @return
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * set value of fileName property
     *
     * @param fileName
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * give value of fileSize property
     *
     * @return
     */
    public long getFileSize() {
        return fileSize;
    }

    /**
     * set value of fileSize property
     *
     * @param fileSize
     */
    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * give value of fileType property
     *
     * @return
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * set value of fileType property
     *
     * @param fileType
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * give value of mainObject property
     *
     * @return
     */
    public FileMetaJsonResponse getMainObject() {
        return mainObject;
    }

    /**
     * set value of mainObject property
     *
     * @param mainObject
     */
    public void setMainObject(FileMetaJsonResponse mainObject) {
        this.mainObject = mainObject;
    }

    /**
     * get value of operatingSystem property
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * set value of operatingSystem property
     *
     * @param operatingSystem
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

     /**
     * gets Unique filename
     * @return 
     */
    public String getUniqueFileName() {
        return UniqueFileName;
    }

    /**
     * sets Unique filename
     * @param UniqueFileName 
     */
    public void setUniqueFileName(String UniqueFileName) {
        this.UniqueFileName = UniqueFileName;
    }

    /**
     * gets fileBytes
     * @return 
     */
    public byte[] getFileBytes() {
        return fileBytes;
    }

    /**
     * sets fileBytes
     * @param fileBytes 
     */
    public void setFileBytes(byte[] fileBytes) {
        this.fileBytes = fileBytes;
    }

    /**
     * gets Status
     * @return 
     */
    public String getStatus() {
        return status;
    }

    /**
     * sets status
     * @param status 
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * gets the file to be uploaded
     * @return 
     */
    public File getFile() {
        return file;
    }

    /**
     * sets the file to be uploaded
     * @param file 
     */
    public void setFile(File file) {
        this.file = file;
    }

    /**
     * gets folderName on server to be zipped
     * @return 
     */
    public String getFolderOnServer() {
        return folderOnServer;
    }

    /**
     * sets folder name on server
     * @param folderOnServer 
     */
    public void setFolderOnServer(String folderOnServer) {
        this.folderOnServer = folderOnServer;
    }
    /**
     * method generate hashcode of object based on uuid
     *
     * @return
     */
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.uuid);
        return hash;
    }

    /**
     * methods check equality of object based on uuid of object
     *
     * @param obj
     * @return
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FileMetaJsonResponse other = (FileMetaJsonResponse) obj;
        if (!Objects.equals(this.uuid, other.uuid)) {
            return false;
        }
        return true;
    }
}
